drop node coord1;
drop node coord2;
drop node node1;
drop node node2;
drop node group gp1;
drop node group gp2;
create node coord1 with(TYPE='coordinator',HOST='localhost',PORT=2921);
create node coord2 with(TYPE='coordinator',HOST='localhost',PORT=2922);
create node node1 with(TYPE='datanode',HOST='localhost',PORT=25431,primary=false);
create node node2 with(TYPE='datanode',HOST='localhost',PORT=25432,primary=false);
alter node coord1 with(TYPE='coordinator',HOST='localhost',PORT=2921);
alter node coord2 with(TYPE='coordinator',HOST='localhost',PORT=2922);
alter node node1 with(TYPE='datanode',HOST='localhost',PORT=25431,primary=true);
alter node node2 with(TYPE='datanode',HOST='localhost',PORT=25432,primary=false);
create node group gp1 with(node1);
create node group gp2 with(node2);
select pgxc_pool_reload();
select * from pgxc_node;
